### PR TITLE
Strings added in build 2020103001 later

### PR DESCRIPTION
**Pull request by treastrain**
Add new items

### CODE REVIEW

**Comment by w41k3rc0m** [comment]
@treastrain Thanks for the screenshots! Really helped with the translations. Though I'm not too sure about this line:

> "金属製の机の上やケース・バンパーを装着している場合、……"

Does this mean something like "if you have a case or bumper on your metal phone"?

**Edit:** or "if you have a metal case or bumper on your phone"?

**Comment by treastrain** [comment]
@w41k3rc0m

Thanks. That means "if you have a metal case or bumper on your phone" right. It explains, if a metal case or bumper on the phone, an error may occur due to NFC radio interference.

**Comment by treastrain** [comment]
\+ metal desk etc.

**Pull request merged**
